# Generated by Django 5.1.3 on 2024-11-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
